dist: xenial
language: python
git:
  depth: false
python:
    - "3.7"
install:
    - pip install -r requirements.txt
# command to run tests
script:
    - pytest --cov=turing --cov-report term turing/tests/
branches:
  only:
   - master
# after_success:
# - coveralls
notifications:
  email:
    recipients:
      - magsilva@gmail.com
    on_success: always
on_failure: always
